language: ruby
cache:
  bundler: true
rvm:
  - 2.6.3

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

install:
  - bundle install

script:
  - jekyll build