# Site settings
title: MSUM ACM
baseurl: "" # the subpath of your site, e.g. /blog/
rough: pygments
url :   http://msum-acm.github.io/
permalink: /:year/:month/:day/:title
markdown: kramdown
timezone: America/Chicago
rdiscount:
    extensions: [smart]
