# Site settings
title: MSUM ACM
baseurl: "" # the subpath of your site, e.g. /blog/
rough: pygments
url :   http://msumacm.org
permalink: /:year/:month/:day/:title
markdown: kramdown
timezone: America/Chicago
rdiscount:
    extensions: [smart]
